name: Test Github Action

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Greeting to be downloaded'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create JSON File
        run: |
          python main.py

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: build/data.json

      - name: Printing message
        run: |
          echo "Hello ${{ inputs.name }}"

  silicon-test:
    needs: build
    uses: ./.github/workflows/silicon_test.yml
    secrets: inherit
    with:
      artifact-name: data
      dir-url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.2/npp.8.9.2.portable.x64.zip
