name: Silicon Hardware Testing

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      dir-url:
        required: true
        type: string

jobs:

# -----------------------------
# JOB 1 - Install Driver
# -----------------------------

  install-driver:

    runs-on: [self-hosted, windows]

    env:
      BASE_DIR: D:\MyProjects\githubworkflow
      DRIVER_ZIP: npp.8.9.2.portable.x64.zip

      DRIVER_DIR: D:\MyProjects\githubworkflow\notepad

      FIRMWARE_NAME: data.json

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Download firmware artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: artifact


    - name: Verify firmware
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |
        if (!(Test-Path "artifact\${{ env.FIRMWARE_NAME }}")) {
            Write-Error "Firmware binary missing"
            exit 1
        }


    - name: Ensure base directory exists
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |
        if (!(Test-Path "${{ env.BASE_DIR }}")) {
            New-Item -ItemType Directory -Path "${{ env.BASE_DIR }}"
        }


    - name: Clean old packages
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |

        $driverZip="${{ env.BASE_DIR }}\${{ env.DRIVER_ZIP }}"

        if (Test-Path $driverZip) { Remove-Item $driverZip -Force }

        if (Test-Path "${{ env.DRIVER_DIR }}") {
            Remove-Item "${{ env.DRIVER_DIR }}" -Recurse -Force
        }

    - name: Download driver.zip from Artifactory
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |
        Invoke-WebRequest `
        -Uri "${{ inputs.dir-url }}" `
        -OutFile "${{ env.BASE_DIR }}\${{ env.DRIVER_ZIP }}"
    
    - name: Ensure driver directory exists
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |
        if (!(Test-Path "${{ env.DRIVER_DIR }}")) {
          New-Item -ItemType Directory -Path "${{ env.DRIVER_DIR }}"
        }

    - name: Extract driver package
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |
        Expand-Archive `
          -Path "${{ env.BASE_DIR }}\${{ env.DRIVER_ZIP }}" `
          -DestinationPath "${{ env.DRIVER_DIR }}"

    - name: Replace firmware in driver
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |

        $source="artifact\${{ env.FIRMWARE_NAME }}"
        $destination="${{ env.DRIVER_DIR }}\${{ env.FIRMWARE_NAME }}"

        Copy-Item $source $destination -Force


    - name: Reboot SUT
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |
        echo "rebooting system"


# -----------------------------
# JOB 2 - Silicon Testing
# -----------------------------

  run-silicon-tests:

    needs: install-driver

    runs-on: [self-hosted, windows]

    env:
      DRIVER_DIR: D:\MyProjects\githubworkflow

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Wait for system to stabilize
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |

        Write-Host "Waiting for system to fully boot..."

        Start-Sleep -Seconds 60


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Run silicon tests
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: |

        echo "Running test package"
        python run_test.py


    - name: Silicon tests completed
      shell: powershell -ExecutionPolicy Bypass -Command "{0}"
      run: echo "Silicon testing completed successfully"